// `.open-next/worker.js` is generated by `pnpm cf:build` — it may or may not
// exist yet (e.g. a fresh clone), so `@ts-ignore` (not `@ts-expect-error`,
// which would itself error once the file does exist) is correct here.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { default as handler } from "./.open-next/worker.js";

import { createDb } from "@/lib/db";
import { runAbandonedCartReminders } from "@/lib/abandoned-carts/run";

/**
 * Wraps the OpenNext-generated fetch handler with a `scheduled()` handler
 * for the abandoned-cart Cron Trigger (tasks/phase-14-advanced/92-abandoned-
 * carts.md) — see wrangler.jsonc `main` / `triggers.crons`, and
 * https://opennext.js.org/cloudflare/howtos/custom-worker for the pattern.
 */
export default {
  fetch: handler.fetch,

  async scheduled(_controller, env: CloudflareEnv) {
    const db = createDb(env.DB);
    await runAbandonedCartReminders(db);
  },
} satisfies ExportedHandler<CloudflareEnv>;
