/**
 * Generates a SQL file that seeds D1 with the Faker-generated mock catalog,
 * for development only (AGENTS.md "No fake data": seed data must stay
 * clearly separate from production data and only exists because this task
 * explicitly asked for it).
 *
 * This does not talk to D1 directly — D1Database is a Workers runtime
 * binding, not reachable from a plain Node script — it writes SQL that
 * `wrangler d1 execute` then applies. See the `db:seed:*` scripts in
 * package.json.
 *
 * Re-running this is safe: generated SQL deletes existing rows (in
 * dependency order) before inserting, and `generateMockCatalog()` uses a
 * fixed Faker seed, so output is stable across runs.
 */
import { mkdirSync, writeFileSync } from "node:fs";

import { generateMockCatalog } from "../lib/catalog/generate-mock-catalog";

function str(value: string | null | undefined): string {
  if (value === null || value === undefined) {
    return "NULL";
  }
  return `'${value.replace(/'/g, "''")}'`;
}

function num(value: number | null | undefined): string {
  return value === null || value === undefined ? "NULL" : String(value);
}

function bool(value: boolean): string {
  return value ? "1" : "0";
}

function json(value: unknown): string {
  return str(JSON.stringify(value));
}

const catalog = generateMockCatalog();
const lines: string[] = [
  "-- Generated by scripts/generate-seed-sql.ts — do not hand-edit.",
  "-- Development seed data only. Never run db:seed:remote against a real production database.",
];

lines.push(
  "DELETE FROM kit_components;",
  "DELETE FROM project_components;",
  "DELETE FROM inventory;",
  "DELETE FROM product_images;",
  "DELETE FROM product_variants;",
  "DELETE FROM kits;",
  "DELETE FROM products;",
  "DELETE FROM robot_projects;",
  "DELETE FROM categories;",
);

for (const c of catalog.categories) {
  lines.push(
    `INSERT INTO categories (id, name, slug, description, sort_order, created_at, updated_at) VALUES (${str(c.id)}, ${str(c.name)}, ${str(c.slug)}, ${str(c.description)}, ${num(c.sortOrder)}, ${str(c.createdAt)}, ${str(c.updatedAt)});`,
  );
}

for (const p of catalog.products) {
  lines.push(
    `INSERT INTO products (id, name, slug, sku, description, short_description, brand, category_id, price, compare_at_price, weight_grams, status, featured, specifications, created_at, updated_at) VALUES (${str(p.id)}, ${str(p.name)}, ${str(p.slug)}, ${str(p.sku)}, ${str(p.description)}, ${str(p.shortDescription)}, ${str(p.brand)}, ${str(p.categoryId)}, ${num(p.price)}, ${num(p.compareAtPrice)}, ${num(p.weightGrams)}, ${str(p.status)}, ${bool(p.featured)}, ${json(p.specifications)}, ${str(p.createdAt)}, ${str(p.updatedAt)});`,
  );
}

for (const v of catalog.variants) {
  lines.push(
    `INSERT INTO product_variants (id, product_id, name, sku, price, sort_order, created_at, updated_at) VALUES (${str(v.id)}, ${str(v.productId)}, ${str(v.name)}, ${str(v.sku)}, ${num(v.price)}, ${num(v.sortOrder)}, ${str(v.createdAt)}, ${str(v.updatedAt)});`,
  );
}

for (const img of catalog.images) {
  lines.push(
    `INSERT INTO product_images (id, product_id, url, alt, sort_order, created_at) VALUES (${str(img.id)}, ${str(img.productId)}, ${str(img.url)}, ${str(img.alt)}, ${num(img.sortOrder)}, CURRENT_TIMESTAMP);`,
  );
}

for (const row of catalog.inventory) {
  lines.push(
    `INSERT INTO inventory (id, product_id, variant_id, sku, stock_quantity, reserved_quantity, low_stock_threshold, created_at, updated_at) VALUES (${str(crypto.randomUUID())}, ${str(row.productId)}, ${str(row.variantId)}, ${str(row.sku)}, ${num(row.stockQuantity)}, ${num(row.reservedQuantity)}, ${num(row.lowStockThreshold)}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);`,
  );
}

for (const proj of catalog.projects) {
  lines.push(
    `INSERT INTO robot_projects (id, name, slug, description, short_description, skill_level, status, featured, image_url, image_alt, created_at, updated_at) VALUES (${str(proj.id)}, ${str(proj.name)}, ${str(proj.slug)}, ${str(proj.description)}, ${str(proj.shortDescription)}, ${str(proj.skillLevel)}, ${str(proj.status)}, ${bool(proj.featured)}, ${str(proj.imageUrl)}, ${str(proj.imageAlt)}, ${str(proj.createdAt)}, ${str(proj.updatedAt)});`,
  );
}

for (const kit of catalog.kits) {
  lines.push(
    `INSERT INTO kits (id, name, slug, description, short_description, price, compare_at_price, status, project_id, featured, image_url, image_alt, created_at, updated_at) VALUES (${str(kit.id)}, ${str(kit.name)}, ${str(kit.slug)}, ${str(kit.description)}, ${str(kit.shortDescription)}, ${num(kit.price)}, ${num(kit.compareAtPrice)}, ${str(kit.status)}, ${str(kit.projectId)}, ${bool(kit.featured)}, ${str(kit.imageUrl)}, ${str(kit.imageAlt)}, ${str(kit.createdAt)}, ${str(kit.updatedAt)});`,
  );
}

for (const kc of catalog.kitComponents) {
  lines.push(
    `INSERT INTO kit_components (id, kit_id, product_id, variant_id, quantity, created_at) VALUES (${str(kc.id)}, ${str(kc.kitId)}, ${str(kc.productId)}, ${str(kc.variantId)}, ${num(kc.quantity)}, CURRENT_TIMESTAMP);`,
  );
}

for (const pc of catalog.projectComponents) {
  lines.push(
    `INSERT INTO project_components (id, project_id, product_id, variant_id, quantity, optional, created_at) VALUES (${str(pc.id)}, ${str(pc.projectId)}, ${str(pc.productId)}, ${str(pc.variantId)}, ${num(pc.quantity)}, ${bool(pc.optional)}, CURRENT_TIMESTAMP);`,
  );
}

mkdirSync(".seed", { recursive: true });
writeFileSync(".seed/seed.sql", lines.join("\n") + "\n");

console.log(
  `Wrote ${catalog.categories.length} categories, ${catalog.products.length} products, ${catalog.variants.length} variants, ${catalog.images.length} images, ${catalog.inventory.length} inventory rows, ${catalog.projects.length} projects, ${catalog.kits.length} kits, ${catalog.kitComponents.length} kit components, ${catalog.projectComponents.length} project components to .seed/seed.sql`,
);
